/* ============================================================
   Job Notification Tracker — Mock Data
   ============================================================
   60 realistic Indian tech job listings.
   ============================================================ */

window.JOB_DATA = [
    /* ── INTERNSHIPS (15) ───────────────────────────────────── */
    {
        id: 'int-001',
        title: 'SDE Intern',
        company: 'Amazon',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Java', 'DSA', 'AWS'],
        source: 'LinkedIn',
        postedDaysAgo: 1,
        salaryRange: '₹40k–₹80k/month',
        applyUrl: 'https://amazon.jobs',
        description: 'Join the Amazon Kindle team as an SDE Intern. You will work on scalable backend services and distributed systems. Ideal for final year students with strong DSA skills.'
    },
    {
        id: 'int-002',
        title: 'Frontend Engineering Intern',
        company: 'Razorpay',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['React', 'JavaScript', 'CSS'],
        source: 'Razorpay Careers',
        postedDaysAgo: 2,
        salaryRange: '₹30k–₹50k/month',
        applyUrl: 'https://razorpay.com/jobs',
        description: 'Work with the Checkout team to build seamless payment experiences. You will contribute to our React codebase and learn modern frontend practices.'
    },
    {
        id: 'int-003',
        title: 'Backend Intern',
        company: 'Swiggy',
        location: 'Remote',
        mode: 'Remote',
        experience: 'Fresher',
        skills: ['Go', 'SQL', 'Microservices'],
        source: 'Instahyre',
        postedDaysAgo: 0,
        salaryRange: '₹35k–₹60k/month',
        applyUrl: 'https://careers.swiggy.com',
        description: 'Assist in building high-throughput delivery APIs. Experience with Go or Python is a plus. Remote friendly role for 6 months.'
    },
    {
        id: 'int-004',
        title: 'Data Science Intern',
        company: 'PhonePe',
        location: 'Pune',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Python', 'SQL', 'Pandas'],
        source: 'LinkedIn',
        postedDaysAgo: 3,
        salaryRange: '₹40k/month',
        applyUrl: 'https://phonepe.com/careers',
        description: 'Analyze transaction data to detect fraud patterns. Strong statistical foundation and Python proficiency required.'
    },
    {
        id: 'int-005',
        title: 'Product Design Intern',
        company: 'CRED',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Figma', 'UI Design', 'Prototyping'],
        source: 'Dribbble',
        postedDaysAgo: 5,
        salaryRange: '₹50k–₹70k/month',
        applyUrl: 'https://cred.club/careers',
        description: 'Design beautiful, darker-mode interfaces for the CRED app. Portfolio demonstrating high-fidelity UI work is mandatory.'
    },
    {
        id: 'int-006',
        title: 'QA Automation Intern',
        company: 'Zoho',
        location: 'Chennai',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Java', 'Selenium', 'Testing'],
        source: 'Zoho Careers',
        postedDaysAgo: 1,
        salaryRange: '₹15k–₹25k/month',
        applyUrl: 'https://zoho.com/careers',
        description: 'Learn automation testing frameworks with the Zoho CRM team. Good logical reasoning and Java basics needed.'
    },
    {
        id: 'int-007',
        title: 'Winter Software Intern',
        company: 'Google',
        location: 'Hyderabad',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['C++', 'Python', 'Algorithms'],
        source: 'Google Careers',
        postedDaysAgo: 7,
        salaryRange: '₹80k–₹1L/month',
        applyUrl: 'https://careers.google.com',
        description: 'Work on Google Cloud Platform features. Requires excellent problem-solving skills and proficiency in C++ or Java.'
    },
    {
        id: 'int-008',
        title: 'Full Stack Intern',
        company: 'Zomato',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['React', 'Node.js', 'MongoDB'],
        source: 'Naukri',
        postedDaysAgo: 4,
        salaryRange: '₹25k–₹40k/month',
        applyUrl: 'https://zomato.com/careers',
        description: 'Contribute to Zomato dining app features. Full stack JS knowledge (MERN) preferred.'
    },
    {
        id: 'int-009',
        title: 'Android Dev Intern',
        company: 'Flipkart',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Kotlin', 'Android Studio', 'XML'],
        source: 'LinkedIn',
        postedDaysAgo: 2,
        salaryRange: '₹50k/month',
        applyUrl: 'https://flipkartcareers.com',
        description: 'Build features for the Flipkart Android app used by millions. Kotlin proficiency is a must.'
    },
    {
        id: 'int-010',
        title: 'DevOps Intern',
        company: 'Paytm',
        location: 'Noida',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Linux', 'Docker', 'Bash'],
        source: 'Paytm Careers',
        postedDaysAgo: 6,
        salaryRange: '₹20k–₹30k/month',
        applyUrl: 'https://paytm.com/careers',
        description: 'Help manage our CI/CD pipelines and cloud infrastructure. Great opportunity to learn Kubernetes and AWS.'
    },
    {
        id: 'int-011',
        title: 'Machine Learning Intern',
        company: 'Microsoft',
        location: 'Hyderabad',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['PyTorch', 'NLP', 'Python'],
        source: 'Microsoft Careers',
        postedDaysAgo: 8,
        salaryRange: '₹80k–₹1L/month',
        applyUrl: 'https://careers.microsoft.com',
        description: 'Research role in the Bing team focusing on NLP models. Masters/PhD students preferred but open to exceptional undergrads.'
    },
    {
        id: 'int-012',
        title: 'Research Intern',
        company: 'Adobe',
        location: 'Noida',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Computer Vision', 'C++', 'Python'],
        source: 'Adobe Careers',
        postedDaysAgo: 3,
        salaryRange: '₹60k/month',
        applyUrl: 'https://adobe.com/careers',
        description: 'Work on next-gen Photoshop features using Computer Vision. Strong math background required.'
    },
    {
        id: 'int-013',
        title: 'Web Developer Intern',
        company: 'Freshworks',
        location: 'Chennai',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['HTML', 'CSS', 'Ember.js'],
        source: 'LinkedIn',
        postedDaysAgo: 1,
        salaryRange: '₹25k–₹35k/month',
        applyUrl: 'https://freshworks.com/careers',
        description: 'Build UI components for Freshdesk. We use Ember.js, but React/Vue knowledge is transferable.'
    },
    {
        id: 'int-014',
        title: 'Software Intern',
        company: 'Cisco',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Networking', 'Python', 'C'],
        source: 'Cisco Jobs',
        postedDaysAgo: 5,
        salaryRange: '₹45k–₹60k/month',
        applyUrl: 'https://jobs.cisco.com',
        description: 'Work on networking software and security protocols. Knowledge of TCP/IP and OS concepts is essential.'
    },
    {
        id: 'int-015',
        title: 'Cyber Security Intern',
        company: 'Palo Alto Networks',
        location: 'Bangalore',
        mode: 'Remote',
        experience: 'Fresher',
        skills: ['Network Security', 'Linux', 'Python'],
        source: 'Indeed',
        postedDaysAgo: 2,
        salaryRange: '₹50k/month',
        applyUrl: 'https://paloaltonetworks.com/careers',
        description: 'Analyze security threats and vulnerabilities. Perfect for students interested in cybersecurity and ethical hacking.'
    },

    /* ── FRESHER ROLES (15) ─────────────────────────────────── */
    {
        id: 'fr-001',
        title: 'Systems Engineer',
        company: 'Infosys',
        location: 'Mysore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Java', 'SQL', 'Python'],
        source: 'Naukri',
        postedDaysAgo: 1,
        salaryRange: '3.6–5 LPA',
        applyUrl: 'https://infosys.com/careers',
        description: 'Entry level role for fresh graduates. Includes 3 months of training at Mysore campus. Logic and communication skills tested.'
    },
    {
        id: 'fr-002',
        title: 'Assistant System Engineer',
        company: 'TCS',
        location: 'Mumbai',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['C++', 'DBMS', 'Java'],
        source: 'TCS NQT',
        postedDaysAgo: 0,
        salaryRange: '3.36–7 LPA',
        applyUrl: 'https://tcs.com/careers',
        description: 'Join TCS via the NQT process. Roles assigned based on interview performance (Ninja/Digital/Prime profiles).'
    },
    {
        id: 'fr-003',
        title: 'Project Engineer',
        company: 'Wipro',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['DotNet', 'C#', 'SQL'],
        source: 'LinkedIn',
        postedDaysAgo: 4,
        salaryRange: '3.5–6 LPA',
        applyUrl: 'https://wipro.com/careers',
        description: 'Work on enterprise web applications for banking clients. Training on .NET stack provided.'
    },
    {
        id: 'fr-004',
        title: 'Associate Software Engineer',
        company: 'Accenture',
        location: 'Gurgaon',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Cloud Basics', 'Java', 'Communication'],
        source: 'Naukri',
        postedDaysAgo: 2,
        salaryRange: '4.5–6.5 LPA',
        applyUrl: 'https://accenture.com/careers',
        description: 'Start your career with Accenture technology. Opportunities in SAP, Salesforce, and Full Stack development.'
    },
    {
        id: 'fr-005',
        title: 'Programmer Analyst Trainee',
        company: 'Cognizant',
        location: 'Coimbatore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Java', 'Testing', 'SQL'],
        source: 'Cognizant Careers',
        postedDaysAgo: 3,
        salaryRange: '4–5 LPA',
        applyUrl: 'https://cognizant.com/careers',
        description: 'GenC profile recruitment. You will be trained in Java Full Stack or Automation Testing.'
    },
    {
        id: 'fr-006',
        title: 'Graduate Engineer Trainee',
        company: 'L&T Infotech (LTIMindtree)',
        location: 'Pune',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['C', 'Embedded', 'IoT'],
        source: 'LinkedIn',
        postedDaysAgo: 5,
        salaryRange: '4–5 LPA',
        applyUrl: 'https://ltimindtree.com',
        description: 'Embedded systems role fitting for ECE/EEE graduates. Work on automotive IoT solutions.'
    },
    {
        id: 'fr-007',
        title: 'Associate Engineer',
        company: 'Capgemini',
        location: 'Noida',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Java', 'Cloud', 'Customer Support'],
        source: 'Naukri',
        postedDaysAgo: 6,
        salaryRange: '4–7.5 LPA',
        applyUrl: 'https://capgemini.com/careers',
        description: 'Exciting opportunities in Cloud Infrastructure Services. Rotational shifts may be required.'
    },
    {
        id: 'fr-008',
        title: 'Software Developer (Fresher)',
        company: 'Zoho',
        location: 'Tenkasi',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['C', 'C++', 'Java'],
        source: 'Zoho Careers',
        postedDaysAgo: 1,
        salaryRange: '6–10 LPA',
        applyUrl: 'https://zoho.com/careers',
        description: 'Product development role at Zoho Tenkasi. Heavy focus on core programming logic and data structures.'
    },
    {
        id: 'fr-009',
        title: 'Platform Engineer',
        company: 'Juspay',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Haskell', 'Functional Programming', 'PureScript'],
        source: 'HackerEarth',
        postedDaysAgo: 7,
        salaryRange: '12–16 LPA',
        applyUrl: 'https://juspay.in/careers',
        description: 'Solve complex payment success rate problems. We use Haskell and PureScript. Hiring via Hackathon.'
    },
    {
        id: 'fr-010',
        title: 'SDE-1',
        company: 'Groww',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Java', 'Spring Boot', 'Microservices'],
        source: 'LinkedIn',
        postedDaysAgo: 1,
        salaryRange: '14–18 LPA',
        applyUrl: 'https://groww.in/careers',
        description: 'Backend role for fresh graduates with strong internship experience. Build scalable fintech systems.'
    },
    {
        id: 'fr-011',
        title: 'Junior Data Analyst',
        company: 'Mu Sigma',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Statistics', 'R', 'Excel'],
        source: 'Campus Drive',
        postedDaysAgo: 8,
        salaryRange: '5–7 LPA',
        applyUrl: 'https://mu-sigma.com',
        description: 'Decision science role. Intensive training program involved. Bond agreement applicable.'
    },
    {
        id: 'fr-012',
        title: 'Technical Support Engineer',
        company: 'Dell',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Networking', 'Linux', 'Troubleshooting'],
        source: 'Dell Jobs',
        postedDaysAgo: 2,
        salaryRange: '5–6 LPA',
        applyUrl: 'https://jobs.dell.com',
        description: 'Provide enterprise support for Dell servers and storage. Good debugging skills needed.'
    },
    {
        id: 'fr-013',
        title: 'Software Engineer',
        company: 'HCLTech',
        location: 'Lucknow',
        mode: 'Onsite',
        experience: 'Fresher',
        skills: ['Java', 'SQL'],
        source: 'Naukri',
        postedDaysAgo: 3,
        salaryRange: '3.5–4.5 LPA',
        applyUrl: 'https://hcltech.com/careers',
        description: 'Java developer role for HCL Lucknow campus. Local candidates preferred.'
    },
    {
        id: 'fr-014',
        title: 'Frontend Developer',
        company: 'Tech Mahindra',
        location: 'Pune',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Angular', 'TypeScript', 'HTML'],
        source: 'LinkedIn',
        postedDaysAgo: 4,
        salaryRange: '3.25–4 LPA',
        applyUrl: 'https://techmahindra.com',
        description: 'Frontend role requiring Angular knowledge. Immediate joiners preferred.'
    },
    {
        id: 'fr-015',
        title: 'Analyst',
        company: 'Deloitte',
        location: 'Hyderabad',
        mode: 'Hybrid',
        experience: 'Fresher',
        skills: ['Python', 'SQL', 'Tableau'],
        source: 'Deloitte Careers',
        postedDaysAgo: 2,
        salaryRange: '6–8 LPA',
        applyUrl: 'https://deloitte.com/careers',
        description: 'Risk and Financial Advisory analyst. Good communication and analytical skills required.'
    },

    /* ── JUNIOR ROLES (0-2 YOE) (15) ────────────────────────── */
    {
        id: 'jr-001',
        title: 'React Developer',
        company: 'CarDekho',
        location: 'Gurgaon',
        mode: 'Hybrid',
        experience: '0-1 Years',
        skills: ['React', 'Redux', 'JavaScript'],
        source: 'Naukri',
        postedDaysAgo: 2,
        salaryRange: '6–9 LPA',
        applyUrl: 'https://cardekho.com',
        description: 'Build user-facing features for CarDekho web. 1 year experience with React required.'
    },
    {
        id: 'jr-002',
        title: 'Java Developer',
        company: 'Oracle',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '1-2 Years',
        skills: ['Java 8', 'Spring Boot', 'Rest API'],
        source: 'Oracle Careers',
        postedDaysAgo: 4,
        salaryRange: '10–16 LPA',
        applyUrl: 'https://oracle.com/careers',
        description: 'Oracle Financial Services team. Need strong Java 8+ and Spring Boot understanding.'
    },
    {
        id: 'jr-003',
        title: 'Data Engineer',
        company: 'Fractal',
        location: 'Mumbai',
        mode: 'Onsite',
        experience: '1-3 Years',
        skills: ['Spark', 'Python', 'SQL'],
        source: 'LinkedIn',
        postedDaysAgo: 3,
        salaryRange: '8–12 LPA',
        applyUrl: 'https://fractal.ai',
        description: 'ETL pipeline development using PySpark. Experience with Azure Data Factory is a bonus.'
    },
    {
        id: 'jr-004',
        title: 'iOS Developer',
        company: 'Swiggy',
        location: 'Bangalore',
        mode: 'Remote',
        experience: '1-2 Years',
        skills: ['Swift', 'iOS SDK', 'UIKit'],
        source: 'Swiggy Careers',
        postedDaysAgo: 1,
        salaryRange: '12–18 LPA',
        applyUrl: 'https://swiggy.com',
        description: 'Work on Swiggy consumer app. Swift UI knowledge preferred.'
    },
    {
        id: 'jr-005',
        title: 'Backend Engineer',
        company: 'Meesho',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '1-3 Years',
        skills: ['Java', 'Kafka', 'MySQL'],
        source: 'LinkedIn',
        postedDaysAgo: 0,
        salaryRange: '18–25 LPA',
        applyUrl: 'https://meesho.com/careers',
        description: 'High scale backend systems. Experience with caching (Redis) and message queues (Kafka) needed.'
    },
    {
        id: 'jr-006',
        title: 'Associate',
        company: 'JPMorgan Chase',
        location: 'Mumbai',
        mode: 'Hybrid',
        experience: '1-3 Years',
        skills: ['Python', 'Django', 'React'],
        source: 'JPMC Careers',
        postedDaysAgo: 5,
        salaryRange: '14–20 LPA',
        applyUrl: 'https://jpmorganchase.com',
        description: 'Full stack role in Asset Management division. Modern stack (Python/React).'
    },
    {
        id: 'jr-007',
        title: 'QA Engineer',
        company: 'Paytm',
        location: 'Noida',
        mode: 'Onsite',
        experience: '1-2 Years',
        skills: ['Java', 'Appium', 'Selenium'],
        source: 'Indeed',
        postedDaysAgo: 3,
        salaryRange: '7–10 LPA',
        applyUrl: 'https://paytm.com',
        description: 'Mobile automation testing for Paytm app. Experience with Appium required.'
    },
    {
        id: 'jr-008',
        title: 'Frontend Engineer',
        company: 'Udaan',
        location: 'Bangalore',
        mode: 'Remote',
        experience: '1-3 Years',
        skills: ['React', 'TypeScript', 'Web Optimization'],
        source: 'LinkedIn',
        postedDaysAgo: 6,
        salaryRange: '15–22 LPA',
        applyUrl: 'https://udaan.com/careers',
        description: 'Build B2B e-commerce interfaces. Performance optimization experience is key.'
    },
    {
        id: 'jr-009',
        title: 'Support Engineer',
        company: 'Salesforce',
        location: 'Hyderabad',
        mode: 'Hybrid',
        experience: '1-3 Years',
        skills: ['Apex', 'CRM', 'SQL'],
        source: 'Salesforce Careers',
        postedDaysAgo: 2,
        salaryRange: '10–14 LPA',
        applyUrl: 'https://salesforce.com',
        description: 'Premium support for Salesforce Service Cloud. Apex debugging skills needed.'
    },
    {
        id: 'jr-010',
        title: 'PHP Developer',
        company: 'Naukri (Info Edge)',
        location: 'Noida',
        mode: 'Onsite',
        experience: '1-3 Years',
        skills: ['PHP', 'Laravel', 'MySQL'],
        source: 'Naukri',
        postedDaysAgo: 4,
        salaryRange: '6–9 LPA',
        applyUrl: 'https://infoedge.in',
        description: 'Maintain and upgrade legacy PHP systems for Naukri portal.'
    },
    {
        id: 'jr-011',
        title: 'Angular Developer',
        company: 'Capgemini',
        location: 'Pune',
        mode: 'Hybrid',
        experience: '1-3 Years',
        skills: ['Angular 12+', 'RxJS', 'HTML'],
        source: 'LinkedIn',
        postedDaysAgo: 5,
        salaryRange: '5–8 LPA',
        applyUrl: 'https://capgemini.com',
        description: 'Frontend role for a European banking client. Angular 10+ experience mandatory.'
    },
    {
        id: 'jr-012',
        title: 'Data Analyst',
        company: 'Flipkart',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '1-2 Years',
        skills: ['SQL', 'Excel', 'PowerBI'],
        source: 'Flipkart Careers',
        postedDaysAgo: 1,
        salaryRange: '9–13 LPA',
        applyUrl: 'https://flipkart.com',
        description: 'Business analyst for Supply Chain team. Extract insights using SQL and verify with Operations.'
    },
    {
        id: 'jr-013',
        title: 'Network Engineer',
        company: 'Airtel',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: '1-3 Years',
        skills: ['CCNA', 'Networking', '5G'],
        source: 'Airtel Jobs',
        postedDaysAgo: 3,
        salaryRange: '6–8 LPA',
        applyUrl: 'https://airtel.in',
        description: 'Manage network operations center (NOC). Shift work involved.'
    },
    {
        id: 'jr-014',
        title: 'Go Developer',
        company: 'Gojek',
        location: 'Bangalore',
        mode: 'Remote',
        experience: '1-3 Years',
        skills: ['Go', 'gRPC', 'Postgres'],
        source: 'LinkedIn',
        postedDaysAgo: 2,
        salaryRange: '20–28 LPA',
        applyUrl: 'https://gojek.com',
        description: 'Backend role for SuperApp. Go language proficiency required. Excellent compensation.'
    },
    {
        id: 'jr-015',
        title: 'Software Engineer',
        company: 'Samsung',
        location: 'Noida',
        mode: 'Onsite',
        experience: '1-2 Years',
        skills: ['C++', 'Android', 'System Programming'],
        source: 'Samsung Careers',
        postedDaysAgo: 4,
        salaryRange: '10–14 LPA',
        applyUrl: 'https://samsung.com',
        description: 'R&D role for Samsung Mobile devices. C++ system level programming.'
    },

    /* ── MID-SENIOR ROLES (15) ──────────────────────────────── */
    {
        id: 'sr-001',
        title: 'Senior Software Engineer',
        company: 'Uber',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '3-5 Years',
        skills: ['Go', 'System Design', 'Microservices'],
        source: 'Uber Careers',
        postedDaysAgo: 1,
        salaryRange: '35–50 LPA',
        applyUrl: 'https://uber.com/careers',
        description: 'Core infrastructure team. Heavy focus on distributed systems and high availability.'
    },
    {
        id: 'sr-002',
        title: 'SDE-2',
        company: 'Amazon',
        location: 'Hyderabad',
        mode: 'Hybrid',
        experience: '3-5 Years',
        skills: ['Java', 'DynamoDB', 'AWS'],
        source: 'Amazon Jobs',
        postedDaysAgo: 3,
        salaryRange: '30–45 LPA',
        applyUrl: 'https://amazon.jobs',
        description: 'Amazon Prime Video team. Build low latency streaming services.'
    },
    {
        id: 'sr-003',
        title: 'Lead Engineer',
        company: 'MakeMyTrip',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: '4-7 Years',
        skills: ['Java', 'Redis', 'ElasticSearch'],
        source: 'LinkedIn',
        postedDaysAgo: 2,
        salaryRange: '25–40 LPA',
        applyUrl: 'https://makemytrip.com',
        description: 'Lead the flight search engine team. Optimize search latency and caching strategies.'
    },
    {
        id: 'sr-004',
        title: 'Senior Frontend Dev',
        company: 'Atlassian',
        location: 'Bangalore',
        mode: 'Remote',
        experience: '3-6 Years',
        skills: ['React', 'GraphQL', 'Performance'],
        source: 'Atlassian Careers',
        postedDaysAgo: 5,
        salaryRange: '30–48 LPA',
        applyUrl: 'https://atlassian.com',
        description: 'Jira Cloud frontend team. Work on complex SPA architecture.'
    },
    {
        id: 'sr-005',
        title: 'Staff Engineer',
        company: 'ShareChat',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '5+ Years',
        skills: ['Node.js', 'System Architecture', 'GCP'],
        source: 'LinkedIn',
        postedDaysAgo: 0,
        salaryRange: '45–60 LPA',
        applyUrl: 'https://sharechat.com',
        description: 'Architect scalable backend systems for 100M+ users. Node.js expert required.'
    },
    {
        id: 'sr-006',
        title: 'Tech Lead',
        company: 'Paytm',
        location: 'Noida',
        mode: 'Onsite',
        experience: '4-7 Years',
        skills: ['Java', 'Spring Boot', 'Team Leading'],
        source: 'Naukri',
        postedDaysAgo: 4,
        salaryRange: '25–35 LPA',
        applyUrl: 'https://paytm.com',
        description: 'Lead a team of 5-8 developers for Payment Gateway integration.'
    },
    {
        id: 'sr-007',
        title: 'Senior Data Scientist',
        company: 'Walmart Global Tech',
        location: 'Bangalore',
        mode: 'Hybrid',
        experience: '3-6 Years',
        skills: ['Python', 'Machine Learning', 'Big Data'],
        source: 'Walmart Careers',
        postedDaysAgo: 2,
        salaryRange: '28–38 LPA',
        applyUrl: 'https://walmart.com',
        description: 'Demand forecasting team. Work with very large datasets and production ML models.'
    },
    {
        id: 'sr-008',
        title: 'DevOps Lead',
        company: 'InMobi',
        location: 'Bangalore',
        mode: 'Remote',
        experience: '4-8 Years',
        skills: ['Kubernetes', 'Terraform', 'Azure'],
        source: 'LinkedIn',
        postedDaysAgo: 6,
        salaryRange: '30–45 LPA',
        applyUrl: 'https://inmobi.com',
        description: 'Manage multi-cloud infrastructure (Azure/AWS). Kubernetes expertise mandatory.'
    },
    {
        id: 'sr-009',
        title: 'SAP Consultant',
        company: 'IBM',
        location: 'Kolkata',
        mode: 'Onsite',
        experience: '3-5 Years',
        skills: ['SAP ABAP', 'HANA', 'Fiori'],
        source: 'IBM Careers',
        postedDaysAgo: 3,
        salaryRange: '12–18 LPA',
        applyUrl: 'https://ibm.com',
        description: 'SAP implementation project for global retail client. ABAP on HANA experience needed.'
    },
    {
        id: 'sr-010',
        title: 'Senior QA Engineer',
        company: 'Ola',
        location: 'Bangalore',
        mode: 'Onsite',
        experience: '3-5 Years',
        skills: ['Appium', 'Java', 'Automation Frameworks'],
        source: 'Ola Careers',
        postedDaysAgo: 1,
        salaryRange: '15–20 LPA',
        applyUrl: 'https://olacabs.com',
        description: 'Test Automation for Ola Electric app. Build custom frameworks from scratch.'
    },
    {
        id: 'sr-011',
        title: 'Cyber Security Analyst',
        company: 'Wipro',
        location: 'Pune',
        mode: 'Hybrid',
        experience: '3-6 Years',
        skills: ['SOC', 'SIEM', 'Splunk'],
        source: 'Naukri',
        postedDaysAgo: 5,
        salaryRange: '10–15 LPA',
        applyUrl: 'https://wipro.com',
        description: 'L2 Security Analyst role. Monitor SIEM alerts and handle incident response.'
    },
    {
        id: 'sr-012',
        title: 'Cloud Architect',
        company: 'TCS',
        location: 'Chennai',
        mode: 'Hybrid',
        experience: '8-12 Years',
        skills: ['AWS', 'Architecture', 'Migration'],
        source: 'TCS Careers',
        postedDaysAgo: 2,
        salaryRange: '18–24 LPA',
        applyUrl: 'https://tcs.com',
        description: 'Architect migration of legacy apps to AWS Cloud. Certification required.'
    },
    {
        id: 'sr-013',
        title: 'Product Manager',
        company: 'Zomato',
        location: 'Gurgaon',
        mode: 'Onsite',
        experience: '3-5 Years',
        skills: ['Product Management', 'Analytics', 'UX'],
        source: 'LinkedIn',
        postedDaysAgo: 4,
        salaryRange: '25–40 LPA',
        applyUrl: 'https://zomato.com',
        description: 'Manage dining out retention products. Data-driven decision making key.'
    },
    {
        id: 'sr-014',
        title: 'Blockchain Developer',
        company: 'Polygon',
        location: 'Remote',
        mode: 'Remote',
        experience: '2-5 Years',
        skills: ['Solidity', 'Ethereum', 'Web3.js'],
        source: 'Web3 Jobs',
        postedDaysAgo: 1,
        salaryRange: '40–80 LPA',
        applyUrl: 'https://polygon.technology',
        description: 'Core protocol development. Deep understanding of EVM and smart contracts.'
    },
    {
        id: 'sr-015',
        title: 'Senior UI/UX Designer',
        company: 'PhonePe',
        location: 'Bangalore',
        mode: 'Office',
        experience: '4-7 Years',
        skills: ['Figma', 'User Research', 'Design Systems'],
        source: 'Dribbble',
        postedDaysAgo: 3,
        salaryRange: '25–35 LPA',
        applyUrl: 'https://phonepe.com',
        description: 'Lead design for wealth management products. Maintenance of design system involved.'
    }
];
